baseURL: https://julien-marecaux-portfolio.netlify.app
languageCode: en-us
title: Portfolio website for Julien Marecaux
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
   #subtitle: |-
   #   A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
  #    AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Julien :)
  blog: {}
  contact:
    address:
      - city: London
        country: Dreamland
        street: Boulevard of broken dreams
        title: Adress
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: guessmyemail@ahahah.com
        title: Email
    enable: yes
    phone:
      - phone: 0123456789
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Julien Corporation
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
    #  - icon: fa-twitter
    #    label: Twitter
       # url:  https://www.twitter/idonthavetwitter.com
    #  - icon: fa-facebook
    #    label: Facebook
    #    url: # https://www.facebook/julien-marecaux.com
      - icon: fa-instagram
        label: Instagram
        url:  https://www.instagram/julienmareaux.com
      - icon: fa-github
        label: GitHub
        url: # https://www.github/julienmarecaux
   #   - icon: fa-linkedin
   #    label: LinkedIn
   #    url: # https://www.linkedin/julienmarecaux.com
  image: ''
  name: Julien Marecaux
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
   #   - name: Generic Blog
    #    url: blogs/ipsum
   #   - name: Elements
    #    url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: julienphoto.jpg
        subtitle: hello
        title: I am julien
        url: blogs/about
      - image: marathon.jpg
        subtitle: marathon in Paris last weekend
        title: Marathon
        url: blogs/marathon
      - image: amsterdam.jpg
        subtitle: Find your stay in amsterdam
        title: airbnbinamsterdam
        url: blogs/airbnbinamsterdam